/**
 * IBMProjectPlanView – renders the full IBM Consulting project plan
 * generated by the AI planning graph.
 *
 * Props:
 *   plan        – IBMProjectPlan object from the API
 *   status      – 'idle' | 'loading' | 'success' | 'error'
 *   error       – error message string
 *   onRetry     – function to call when user clicks Reintentar
 */
import {
  AlertTriangle,
  Award,
  BarChart3,
  BookOpen,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  Cloud,
  Cpu,
  FileText,
  Layers,
  Loader2,
  Printer,
  Shield,
  Users,
} from 'lucide-react';
import { useRef, useState } from 'react';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
const fmtCLP = (n) =>
  typeof n === 'number'
    ? `$${n.toLocaleString('es-CL')} CLP`
    : '—';

const labelSeniority = (value) => ({
  Senior: 'Senior',
  Mid: 'Semi senior',
  Junior: 'Junior',
}[value] || value || '—');

const labelPriority = (value) => ({
  'Must Have': 'Debe tener',
  'Should Have': 'Debería tener',
  'Could Have': 'Podría tener',
}[value] || value || '—');

const labelStatus = (value) => ({
  Accepted: 'Aceptada',
  Proposed: 'Propuesta',
  Deprecated: 'Obsoleta',
}[value] || value || '—');

const labelJourney = (value) => ({
  Delivery: 'Entrega',
  Solutioning: 'Definición de solución',
}[value] || value || '—');

const PRIORITY_COLORS = {
  'Must Have':    { bg: '#161616', text: '#ff6b6b', border: '#ff6b6b' },
  'Should Have':  { bg: '#161616', text: '#f4c430', border: '#f4c430' },
  'Could Have':   { bg: '#161616', text: '#78c1e8', border: '#78c1e8' },
};

const SP_COLOR = (pts) => {
  if (pts <= 2) return '#42be65';
  if (pts <= 5) return '#f4c430';
  return '#ff6b6b';
};

// ---------------------------------------------------------------------------
// Loading / Error guards
// ---------------------------------------------------------------------------
function LoadingState() {
  return (
    <div className="ibm-plan-loading">
      <Loader2 size={40} className="spin" />
      <p>Generando plan IBM Method Workspace…</p>
      <p style={{ fontSize: '0.8rem', color: '#8d8d8d', marginTop: 8 }}>
        El agente está analizando el proyecto con metodología IBM Consulting.
        Esto puede tomar 1-2 minutos.
      </p>
    </div>
  );
}

function ErrorState({ error, onRetry }) {
  return (
    <div className="ibm-plan-error">
      <AlertTriangle size={32} color="#ff6b6b" />
      <p style={{ marginTop: 12, color: '#ff6b6b' }}>{error || 'Error al generar el plan IBM.'}</p>
      {onRetry && (
        <button className="ibm-btn-primary" style={{ marginTop: 16 }} onClick={onRetry}>
          Reintentar
        </button>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Section: Method Card
// ---------------------------------------------------------------------------
function MethodCard({ plan }) {
  const journeyColor = plan.adoption_journey === 'Solutioning' ? '#f4c430' : '#42be65';
  return (
    <section className="ibm-plan-section">
      <h3 className="ibm-plan-section-title">
        <Award size={18} /> Método IBM Recomendado
      </h3>
      <div className="ibm-method-card">
        <div className="ibm-method-badge">
          <span className="ibm-badge-method">{plan.ibm_recommended_method}</span>
          <span className="ibm-badge-sl">{plan.service_line}</span>
          {plan.adoption_journey && (
            <span className="ibm-badge-journey" style={{ borderColor: journeyColor, color: journeyColor }}>
              Viaje de {labelJourney(plan.adoption_journey)}
            </span>
          )}
        </div>
        <p className="ibm-method-rationale">{plan.ibm_method_rationale}</p>
        {plan.tailoring_notes && (
          <p className="ibm-method-tailoring">
            <strong>Ajuste metodológico:</strong> {plan.tailoring_notes}
          </p>
        )}
        <hr className="ibm-divider" />
        <p className="ibm-project-overview">{plan.project_overview}</p>

        {plan.ibm_assets_recommended?.length > 0 && (
          <div style={{ marginTop: 16 }}>
            <span style={{ fontSize: '0.75rem', color: '#8d8d8d', textTransform: 'uppercase', letterSpacing: 1 }}>
              Activos IBM recomendados
            </span>
            <div className="ibm-tags" style={{ marginTop: 6 }}>
              {plan.ibm_assets_recommended.map((a, i) => (
                <span key={i} className="ibm-tag">{a}</span>
              ))}
            </div>
          </div>
        )}
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Section: Team Roles
// ---------------------------------------------------------------------------
function TeamRolesSection({ roles }) {
  if (!roles?.length) return null;
  return (
    <section className="ibm-plan-section">
      <h3 className="ibm-plan-section-title">
        <Users size={18} /> Equipo de Entrega IBM
      </h3>
      <div className="ibm-table-wrap">
        <table className="ibm-table">
          <thead>
            <tr>
              <th>Rol</th>
              <th>Rol IBM Method Workspace</th>
              <th>Experiencia</th>
              <th>Fase</th>
              <th>Semanas</th>
              <th>Tarifa/mes</th>
              <th>Justificación</th>
            </tr>
          </thead>
          <tbody>
            {roles.map((r, i) => (
              <tr key={i}>
                <td style={{ fontWeight: 600, color: '#78c1e8' }}>{r.role_name}</td>
                <td style={{ fontSize: '0.82rem', color: '#c6c6c6' }}>{r.ibm_method_workspace_role}</td>
                <td>
                  <span className={`ibm-seniority ${r.seniority?.toLowerCase()}`}>
                    {labelSeniority(r.seniority)}
                  </span>
                </td>
                <td style={{ fontSize: '0.82rem' }}>{r.phase}</td>
                <td style={{ textAlign: 'center', fontWeight: 600 }}>{r.dedication_weeks} sem.</td>
                <td style={{ color: '#42be65', fontWeight: 600 }}>{fmtCLP(r.monthly_rate_clp)}</td>
                <td style={{ fontSize: '0.8rem', color: '#a8a8a8', maxWidth: 200 }}>{r.justification}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Section: WBS Phases (expandable accordion)
// ---------------------------------------------------------------------------
function WBSSection({ phases }) {
  const [open, setOpen] = useState(new Set([0]));
  if (!phases?.length) return null;
  const toggle = (i) => setOpen(prev => {
    const next = new Set(prev);
    next.has(i) ? next.delete(i) : next.add(i);
    return next;
  });
  return (
    <section className="ibm-plan-section">
      <h3 className="ibm-plan-section-title">
        <Layers size={18} /> WBS — Fases del Proyecto
      </h3>
      <div className="ibm-wbs">
        {phases.map((phase, i) => (
          <div key={i} className="ibm-wbs-phase">
            <button className="ibm-wbs-header" onClick={() => toggle(i)}>
              <span className="ibm-wbs-phase-num">Fase {i + 1}</span>
              <span className="ibm-wbs-phase-name">{phase.phase_name}</span>
              <span className="ibm-wbs-ibm-phase">({phase.ibm_method_phase})</span>
              <span className="ibm-wbs-duration">{phase.duration_weeks} sem.</span>
              <span className="ibm-wbs-chevron">
                {open.has(i) ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
              </span>
            </button>
            {open.has(i) && (
              <div className="ibm-wbs-body">
                {phase.objectives?.length > 0 && (
                  <div className="ibm-wbs-objectives">
                    <strong>Objetivos:</strong>
                    <ul>{phase.objectives.map((o, j) => <li key={j}>{o}</li>)}</ul>
                  </div>
                )}
                {phase.tasks?.length > 0 && (
                  <div className="ibm-wbs-tasks">
                    <strong>Tareas:</strong>
                    <table className="ibm-table ibm-table-sm">
                      <thead>
                        <tr><th>Tarea</th><th>Responsable</th><th>Esfuerzo (días)</th></tr>
                      </thead>
                      <tbody>
                        {phase.tasks.map((t, j) => (
                          <tr key={j}>
                            <td>{t.task}</td>
                            <td style={{ color: '#78c1e8' }}>{t.responsible_role}</td>
                            <td style={{ textAlign: 'center' }}>{t.effort_days} días</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
                {phase.deliverables?.length > 0 && (
                  <div className="ibm-wbs-deliverables">
                    <strong>Entregables:</strong>
                    <div className="ibm-tags">
                      {phase.deliverables.map((d, j) => <span key={j} className="ibm-tag ibm-tag-green">{d}</span>)}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Section: User Stories (grouped by epic)
// ---------------------------------------------------------------------------
function UserStoriesSection({ stories }) {
  if (!stories?.length) return null;

  // Group by epic
  const byEpic = stories.reduce((acc, s) => {
    const e = s.epic || 'Sin épica';
    (acc[e] = acc[e] || []).push(s);
    return acc;
  }, {});

  return (
    <section className="ibm-plan-section">
      <h3 className="ibm-plan-section-title">
        <BookOpen size={18} /> Historias de Usuario — Formato AD-Agile
      </h3>
      {Object.entries(byEpic).map(([epic, epicStories]) => (
        <div key={epic} className="ibm-epic">
          <h4 className="ibm-epic-title">{epic}</h4>
          <div className="ibm-stories-grid">
            {epicStories.map((s, i) => {
              const pc = PRIORITY_COLORS[s.priority] || PRIORITY_COLORS['Should Have'];
              return (
                <div key={i} className="ibm-story-card" style={{ borderTopColor: pc.border }}>
                  <div className="ibm-story-header">
                    <span className="ibm-story-id">{s.id}</span>
                    <span className="ibm-priority-badge" style={{ background: pc.bg, color: pc.text, borderColor: pc.border }}>
                      {labelPriority(s.priority)}
                    </span>
                    <span className="ibm-story-points" style={{ background: SP_COLOR(s.story_points) }}>
                      {s.story_points} pts
                    </span>
                  </div>
                  <p className="ibm-story-body">
                    <strong>Como</strong> {s.as_a}, <strong>quiero</strong> {s.i_want},{' '}
                    <strong>para</strong> {s.so_that}
                  </p>
                  {s.acceptance_criteria?.length > 0 && (
                    <div className="ibm-story-ac">
                      <span className="ibm-ac-label">Criterios de aceptación:</span>
                      <ul>{s.acceptance_criteria.map((ac, j) => <li key={j}>{ac}</li>)}</ul>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </section>
  );
}

// ---------------------------------------------------------------------------
// Section: ADRs (accordion)
// ---------------------------------------------------------------------------
function ADRSection({ adrs }) {
  const [open, setOpen] = useState(new Set([0]));
  if (!adrs?.length) return null;
  const toggle = (i) => setOpen(prev => {
    const next = new Set(prev);
    next.has(i) ? next.delete(i) : next.add(i);
    return next;
  });
  const statusColor = { 'Accepted': '#42be65', 'Proposed': '#f4c430', 'Deprecated': '#ff6b6b' };

  return (
    <section className="ibm-plan-section">
      <h3 className="ibm-plan-section-title">
        <Shield size={18} /> Registros de Decisión Arquitectónica (ADR)
      </h3>
      <div className="ibm-adrs">
        {adrs.map((adr, i) => (
          <div key={i} className="ibm-adr">
            <button className="ibm-adr-header" onClick={() => toggle(i)}>
              <span className="ibm-adr-id">{adr.id}</span>
              <span className="ibm-adr-title">{adr.title}</span>
              <span className="ibm-adr-status" style={{ color: statusColor[adr.status] || '#78c1e8' }}>
                {labelStatus(adr.status)}
              </span>
              {open.has(i) ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
            </button>
            {open.has(i) && (
              <div className="ibm-adr-body">
                <div className="ibm-adr-field">
                  <span className="ibm-adr-label">Contexto</span>
                  <p>{adr.context}</p>
                </div>
                <div className="ibm-adr-field">
                  <span className="ibm-adr-label">Decisión</span>
                  <p style={{ color: '#42be65', fontWeight: 500 }}>{adr.decision}</p>
                </div>
                <div className="ibm-adr-field">
                  <span className="ibm-adr-label">Justificación</span>
                  <p>{adr.rationale}</p>
                </div>
                {adr.alternatives_considered?.length > 0 && (
                  <div className="ibm-adr-field">
                    <span className="ibm-adr-label">Alternativas consideradas</span>
                    <ul>{adr.alternatives_considered.map((a, j) => <li key={j}>{a}</li>)}</ul>
                  </div>
                )}
                <div className="ibm-adr-field">
                  <span className="ibm-adr-label">Consecuencias</span>
                  <p>{adr.consequences}</p>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Section: Cost Estimate
// ---------------------------------------------------------------------------
const PROVIDER_LABEL = { gcp: 'Google Cloud (GCP)', aws: 'Amazon Web Services (AWS)', azure: 'Microsoft Azure', local: 'Infraestructura Local' };

function CostEstimateSection({ cost }) {
  if (!cost) return null;

  const laborTotal = cost.roles_breakdown?.reduce((s, r) => s + (r.total_clp ?? 0), 0) ?? 0;
  const hasCloud = cost.cloud_services?.length > 0;
  const providerLabel = PROVIDER_LABEL[cost.cloud_provider?.toLowerCase()] ?? cost.cloud_provider ?? 'Local';

  return (
    <section className="ibm-plan-section">
      <h3 className="ibm-plan-section-title">
        <CircleDollarSign size={18} /> Estimación de Costos — IBM Consulting Chile
      </h3>

      {/* Savings highlight */}
      <div className="ibm-savings-banner">
        <div className="ibm-savings-block ibm-savings-without">
          <span className="ibm-savings-label">Setup sin plataforma</span>
          <span className="ibm-savings-value">{fmtCLP(cost.setup_cost_without_solution_clp)}</span>
        </div>
        <div className="ibm-savings-arrow">→</div>
        <div className="ibm-savings-block ibm-savings-with">
          <span className="ibm-savings-label">Setup con plataforma</span>
          <span className="ibm-savings-value" style={{ color: '#42be65' }}>{fmtCLP(cost.setup_cost_with_solution_clp)}</span>
        </div>
        <div className="ibm-savings-block ibm-savings-total">
          <span className="ibm-savings-label">Ahorro estimado</span>
          <span className="ibm-savings-value ibm-savings-pct">
            {fmtCLP(cost.estimated_savings_clp)}
            {cost.savings_percentage > 0 && (
              <span className="ibm-pct-badge">{cost.savings_percentage}% menos</span>
            )}
          </span>
        </div>
      </div>

      {/* Roles breakdown */}
      {cost.roles_breakdown?.length > 0 && (
        <div className="ibm-table-wrap" style={{ marginTop: 20 }}>
          <p className="ibm-cost-subsection-title"><Users size={14} /> Equipo — Mano de Obra</p>
          <table className="ibm-table">
            <thead>
              <tr>
                <th>Rol</th>
                <th>Experiencia</th>
                <th>Tarifa/mes</th>
                <th>Duración (meses)</th>
                <th>Total CLP</th>
              </tr>
            </thead>
            <tbody>
              {cost.roles_breakdown.map((r, i) => (
                <tr key={i}>
                  <td style={{ fontWeight: 500 }}>{r.role_name}</td>
                  <td><span className={`ibm-seniority ${r.seniority?.toLowerCase()}`}>{labelSeniority(r.seniority)}</span></td>
                  <td>{fmtCLP(r.monthly_rate_clp)}</td>
                  <td style={{ textAlign: 'center' }}>{r.duration_months} meses</td>
                  <td style={{ color: '#42be65', fontWeight: 600 }}>{fmtCLP(r.total_clp)}</td>
                </tr>
              ))}
              <tr className="ibm-table-subtotal">
                <td colSpan={4} style={{ textAlign: 'right', fontWeight: 600 }}>Subtotal Mano de Obra</td>
                <td style={{ color: '#42be65', fontWeight: 700 }}>{fmtCLP(laborTotal)}</td>
              </tr>
            </tbody>
          </table>
        </div>
      )}

      {/* Cloud infrastructure breakdown */}
      {hasCloud && (
        <div className="ibm-table-wrap" style={{ marginTop: 20 }}>
          <p className="ibm-cost-subsection-title">
            <Cloud size={14} /> Infraestructura Cloud —&nbsp;
            <span className="ibm-cloud-provider-badge">{providerLabel}</span>
          </p>
          <table className="ibm-table">
            <thead>
              <tr>
                <th>Servicio</th>
                <th>Costo mensual</th>
                <th>Duración (meses)</th>
                <th>Setup único</th>
                <th>Total CLP</th>
              </tr>
            </thead>
            <tbody>
              {cost.cloud_services.map((svc, i) => {
                const runTotal = (svc.monthly_cost_clp ?? 0) * (cost.project_duration_months ?? 6);
                return (
                  <tr key={i}>
                    <td style={{ fontWeight: 500 }}>{svc.service}</td>
                    <td>{fmtCLP(svc.monthly_cost_clp)}</td>
                    <td style={{ textAlign: 'center' }}>{cost.project_duration_months} meses</td>
                    <td>{svc.setup_cost_clp > 0 ? fmtCLP(svc.setup_cost_clp) : '—'}</td>
                    <td style={{ color: '#78a9ff', fontWeight: 600 }}>{fmtCLP(runTotal + (svc.setup_cost_clp ?? 0))}</td>
                  </tr>
                );
              })}
              <tr className="ibm-table-subtotal">
                <td colSpan={4} style={{ textAlign: 'right', fontWeight: 600 }}>
                  Subtotal Cloud ({fmtCLP(cost.cloud_monthly_cost_clp)}/mes + {fmtCLP(cost.cloud_setup_cost_clp)} setup)
                </td>
                <td style={{ color: '#78a9ff', fontWeight: 700 }}>{fmtCLP(cost.cloud_total_cost_clp)}</td>
              </tr>
            </tbody>
          </table>
        </div>
      )}

      {/* Grand total */}
      <div className="ibm-grand-total-bar">
        <span className="ibm-grand-total-label">
          TOTAL PROYECTO ({cost.project_duration_months} meses)
          {hasCloud && <span className="ibm-grand-total-breakdown"> Mano de obra + Cloud</span>}
        </span>
        <span className="ibm-grand-total-value">{fmtCLP(cost.total_project_cost_clp)}</span>
      </div>

      {cost.methodology_note && (
        <p className="ibm-cost-note">{cost.methodology_note}</p>
      )}
    </section>
  );
}

// ---------------------------------------------------------------------------
// Section: Project Risks
// ---------------------------------------------------------------------------
function RisksSection({ risks }) {
  if (!risks?.length) return null;
  return (
    <section className="ibm-plan-section">
      <h3 className="ibm-plan-section-title">
        <AlertTriangle size={18} /> Riesgos del Proyecto
      </h3>
      <ul className="ibm-risks-list">
        {risks.map((r, i) => <li key={i}>{r}</li>)}
      </ul>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------
export default function IBMProjectPlanView({ plan, status, error, onRetry }) {
  const planRef = useRef(null);

  function handleExportPdf() {
    const planNode = planRef.current;
    if (!planNode) {
      window.print();
      return;
    }

    const printWindow = window.open('', '_blank', 'width=1024,height=768');
    if (!printWindow) {
      window.print();
      return;
    }

    const styles = Array.from(document.querySelectorAll('link[rel="stylesheet"], style'))
      .map((node) => node.outerHTML)
      .join('\n');

    printWindow.document.open();
    printWindow.document.write(`<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8" />
  <title>Plan IBM Method Workspace</title>
  ${styles}
  <style>
    @page { size: A4 portrait; margin: 12mm 14mm; }
    html, body { background: #fff; margin: 0; min-height: 100%; }
    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .ibm-print-button { display: none !important; }
    .ibm-plan-root { background: #fff !important; color: #161616 !important; width: 100% !important; }
    .ibm-plan-section, .ibm-wbs-phase, tr { break-inside: avoid; page-break-inside: avoid; }
    thead { display: table-header-group; }
  </style>
</head>
<body>
  ${planNode.outerHTML}
</body>
</html>`);
    printWindow.document.close();

    printWindow.onload = () => {
      printWindow.focus();
      printWindow.print();
    };
  }

  if (status === 'loading') return <LoadingState />;
  if (status === 'error') return <ErrorState error={error} onRetry={onRetry} />;
  if (!plan) return null;

  return (
    <div className="ibm-plan-root" ref={planRef}>
      <div className="ibm-plan-hero">
        <Cpu size={28} />
        <div>
          <h2 className="ibm-plan-title">Plan IBM Method Workspace</h2>
          <p className="ibm-plan-subtitle">
            Generado por el agente IA con metodología IBM Consulting
          </p>
        </div>
        <button
          type="button"
          className="ibm-print-button"
          onClick={handleExportPdf}
          title="Exportar como PDF"
        >
          <Printer size={16} />
          Exportar PDF
        </button>
      </div>

      <MethodCard plan={plan} />
      <TeamRolesSection roles={plan.team_roles} />
      <WBSSection phases={plan.wbs_phases} />
      <UserStoriesSection stories={plan.user_stories} />
      <ADRSection adrs={plan.architecture_decisions} />
      <CostEstimateSection cost={plan.cost_estimate} />
      <RisksSection risks={plan.project_risks} />
    </div>
  );
}
